from typing import Optional, Tuple


class PyPriorityQueue:
    def __init__(self) -> None: ...
    def enqueue(self, priority: int, task_type: str, payload: str) -> None: ...
    def dequeue(self) -> Optional[Tuple[int, str, str]]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...


class PyModelSwap:
    def __init__(self) -> None: ...
    def switch_to_planner(self) -> Tuple[str, bool]: ...
    def switch_to_brain(self) -> Tuple[str, bool]: ...
    def switch_to_hands(self) -> Tuple[str, bool]: ...
    def switch_to_judge(self) -> Tuple[str, bool]: ...
    def current_role(self) -> str: ...
