"""
Pyvis v5.1 — Execution Plan for Judge

Hands generates an execution plan along with code, telling Judge/Critic
how to properly test and validate the code.

References: pyovis_v5_1.md section 6 (Thought Instruction)
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from enum import Enum


class ExecutionType(str, Enum):
    """Types of code execution"""

    PYTHON_SCRIPT = "python_script"  # Simple .py execution
    PYTHON_MODULE = "python_module"  # python -m module
    PYTHON_TEST = "python_test"  # pytest/unittest
    FUNCTION_CALL = "function_call"  # Call specific function
    API_SERVER = "api_server"  # Start server, test endpoints
    CLI_COMMAND = "cli_command"  # CLI tool execution


@dataclass
class TestCase:
    """Individual test case for validation"""

    name: str
    description: str
    input_data: Optional[str] = None
    expected_output: Optional[str] = None
    expected_exit_code: int = 0
    timeout_sec: int = 30
    allow_network: bool = False
    check_stdout_contains: Optional[str] = None
    check_stderr_empty: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "input_data": self.input_data,
            "expected_output": self.expected_output,
            "expected_exit_code": self.expected_exit_code,
            "timeout_sec": self.timeout_sec,
            "allow_network": self.allow_network,
            "check_stdout_contains": self.check_stdout_contains,
            "check_stderr_empty": self.check_stderr_empty,
        }


@dataclass
class ExecutionPlan:
    """
    Execution plan generated by Hands for Judge/Critic.
    Tells how to properly test and validate the generated code.
    """

    execution_type: ExecutionType = ExecutionType.PYTHON_SCRIPT
    entry_point: Optional[str] = None  # e.g., "main.py", "app:app", "test_module"
    function_name: Optional[str] = None  # For FUNCTION_CALL type
    command_args: List[str] = field(default_factory=list)  # Additional CLI args
    environment_vars: Dict[str, str] = field(default_factory=dict)
    test_cases: List[TestCase] = field(default_factory=list)
    setup_commands: List[str] = field(
        default_factory=list
    )  # e.g., ["pip install requests"]
    teardown_commands: List[str] = field(default_factory=list)
    expected_files: List[str] = field(
        default_factory=list
    )  # Files that should be created
    pass_criteria: Dict[str, Any] = field(default_factory=dict)

    # Validation metadata
    requires_database: bool = False
    requires_network: bool = False
    requires_gpu: bool = False
    memory_limit_mb: int = 512
    cpu_limit_percent: int = 100

    def to_dict(self) -> Dict[str, Any]:
        return {
            "execution_type": self.execution_type.value,
            "entry_point": self.entry_point,
            "function_name": self.function_name,
            "command_args": self.command_args,
            "environment_vars": self.environment_vars,
            "test_cases": [tc.to_dict() for tc in self.test_cases],
            "setup_commands": self.setup_commands,
            "teardown_commands": self.teardown_commands,
            "expected_files": self.expected_files,
            "pass_criteria": self.pass_criteria,
            "requires_database": self.requires_database,
            "requires_network": self.requires_network,
            "requires_gpu": self.requires_gpu,
            "memory_limit_mb": self.memory_limit_mb,
            "cpu_limit_percent": self.cpu_limit_percent,
        }

    def to_prompt_string(self) -> str:
        """Convert to string for Judge prompt"""
        lines = ["## 실행 계획\n"]

        lines.append(f"실행 유형: {self.execution_type.value}")

        if self.entry_point:
            lines.append(f"진입점: {self.entry_point}")

        if self.function_name:
            lines.append(f"함수명: {self.function_name}")

        if self.command_args:
            lines.append(f"명령어 인자: {' '.join(self.command_args)}")

        if self.environment_vars:
            lines.append("환경 변수:")
            for k, v in self.environment_vars.items():
                lines.append(f"  {k}={v}")

        if self.test_cases:
            lines.append(f"\n테스트 케이스 ({len(self.test_cases)}개):")
            for i, tc in enumerate(self.test_cases, 1):
                lines.append(f"  {i}. {tc.name}: {tc.description}")
                if tc.expected_output:
                    lines.append(f"     예상 출력: {tc.expected_output[:50]}")

        if self.expected_files:
            lines.append(f"\n예상 생성 파일: {', '.join(self.expected_files)}")

        if self.setup_commands:
            lines.append(f"\n사전 설치: {', '.join(self.setup_commands)}")

        return "\n".join(lines)


def create_execution_plan_from_task(
    task: Dict[str, Any],
    code: str,
    pass_criteria: Dict[str, Any],
    pip_packages: Optional[List[str]] = None,
) -> "ExecutionPlan":
    """
    Create an ExecutionPlan from task information.
    This is a helper that Hands can use to generate execution plans.

    Args:
        task: Task dictionary from Planner
        code: Generated code
        pass_criteria: PASS criteria from Planner

    Returns:
        ExecutionPlan instance
    """
    # Detect execution type from code and task
    execution_type = ExecutionType.PYTHON_SCRIPT

    # Check if it's a FastAPI/Flask app
    if "FastAPI" in code or "Flask" in code or "app:app" in task.get("title", ""):
        execution_type = ExecutionType.API_SERVER
    # Check if it's a test file
    elif "test_" in task.get("file_path", "") or "unittest" in code or "pytest" in code:
        execution_type = ExecutionType.PYTHON_TEST
    # Check if it's a CLI tool
    elif "argparse" in code or "click" in code or "typer" in code:
        execution_type = ExecutionType.CLI_COMMAND

    # Create test cases from pass_criteria
    test_cases = []
    for i, (criterion_id, criterion) in enumerate(pass_criteria.items()):
        if isinstance(criterion, str):
            test_cases.append(
                TestCase(
                    name=f"Criterion {i + 1}",
                    description=criterion,
                    expected_exit_code=0,
                )
            )
        elif isinstance(criterion, dict):
            test_cases.append(
                TestCase(
                    name=criterion.get("name", f"Criterion {i + 1}"),
                    description=criterion.get("description", str(criterion)),
                    expected_output=criterion.get("expected_output"),
                    expected_exit_code=criterion.get("expected_exit_code", 0),
                    check_stdout_contains=criterion.get("check_stdout"),
                )
            )

    # import명 → 실제 pip 패키지명 매핑 테이블
    _IMPORT_TO_PIP: Dict[str, str] = {
        "OpenGL": "PyOpenGL",
        "cv2": "opencv-python-headless",
        "PIL": "Pillow",
        "sklearn": "scikit-learn",
        "yaml": "PyYAML",
        "Crypto": "pycryptodome",
        "bs4": "beautifulsoup4",
        "serial": "pyserial",
        "dotenv": "python-dotenv",
        "googleapiclient": "google-api-python-client",
        "jwt": "PyJWT",
        "telegram": "python-telegram-bot",
        "dateutil": "python-dateutil",
        "magic": "python-magic",
        "psycopg2": "psycopg2-binary",
        "fitz": "PyMuPDF",
        "attr": "attrs",
        "flask": "Flask",
        "lxml": "lxml",
        "gi": "PyGObject",
        "wx": "wxPython",
        "skimage": "scikit-image",
        "usb": "pyusb",
        "websocket": "websocket-client",
    }

    # pip_packages가 Hands에서 전달된 경우 우선 사용
    if pip_packages:
        setup_commands = [f"pip install {pkg}" for pkg in pip_packages]
    else:
        # Fallback: import 구문 기반 감지 (import명 → pip명 매핑 적용)
        setup_commands = []
        if "import requests" in code or "from requests" in code:
            setup_commands.append("pip install requests")
        if "import numpy" in code or "from numpy" in code:
            setup_commands.append("pip install numpy")
        if "import pandas" in code or "from pandas" in code:
            setup_commands.append("pip install pandas")
        if "import flask" in code or "from flask" in code:
            setup_commands.append("pip install flask")
        if "import fastapi" in code or "from fastapi" in code:
            setup_commands.append("pip install fastapi uvicorn")
        # import명 → pip 매핑 테이블에 있는 모듈들 삤캐
        for import_name, pip_name in _IMPORT_TO_PIP.items():
            pattern1 = f"import {import_name}"
            pattern2 = f"from {import_name}"
            if pattern1 in code or pattern2 in code:
                setup_commands.append(f"pip install {pip_name}")
    # Detect expected files
    expected_files = []
    import re

    file_creations = re.findall(r'open\(["\']([^"\']+)["\']', code)
    expected_files.extend(file_creations)

    return ExecutionPlan(
        execution_type=execution_type,
        entry_point=task.get("file_path", "main.py"),
        function_name=task.get("function_name"),
        test_cases=test_cases,
        setup_commands=list(set(setup_commands)),  # Remove duplicates
        expected_files=list(set(expected_files)),
        pass_criteria=pass_criteria,
        requires_network=execution_type == ExecutionType.API_SERVER,
    )


# Example usage in Hands:
"""
async def build(self, task, plan, skill_context):
    code = generate_code(...)
    
    # Create execution plan
    exec_plan = create_execution_plan_from_task(
        task=task,
        code=code,
        pass_criteria=pass_criteria
    )
    
    # Return both code and execution plan
    return code, {
        "execution_plan": exec_plan.to_dict(),
        "reasoning": "..."
    }
"""
